server:
  port: 8082

spring:
  application:
    name: quanxiankongzhi
  datasource:
    url: jdbc:mysql://localhost:3307/ai_knowledge_base?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  elasticsearch:
    uris: http://localhost:9200



file:
  upload-dir: ./uploads

milvus:
  host: localhost
  port: 29530

embedding:
  url: http://localhost:8100